spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sell?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true

  jackson:
    #过滤掉所有null的信息
    default-property-inclusion: non_null
#  mvc:
#    view:
#      prefix: /WEB-INF/
#      suffix: .jsp
#前缀
server:
  servlet:
    context-path: /sell
#    日志
logging:
  pattern:
    console: "%d - %msg%n"
  file:
    path: "F:/log/springboot1"
    name: "sell.log"
#  config: classpath:1logback.xml

